### ISSUE TITLE
Dockerfile Optimization

### ISSUE THREAD

**Issue by djarbz** [IOTech17/rport-docker#1]
[This](https://github.com/AC-WhiteGlint/rport-docker/blob/72baf97573ac21f42a82c57d141570314e896627/Dockerfile#L43) line does nothing to optimize the Container Image size.

Instead line 29 should be as follows.
```
RUN export DEBIAN_FRONTEND=noninteractive \
  && apt update \
  && apt install -y --no-install-recommends wget fail2ban iptables supervisor \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by IOTech17** [comment]
Thank you @djarbz I applied you recommendation.
